# La Imagen en la que se basa el proyecto
FROM node
# Creamos El Directorio donde se va a copiar el proyecto
WORKDIR /app/NextJS
# Copiamos el archivo package.json
COPY package.json pnpm-lock.yaml* ./
# Instalamos las dependencias
RUN pnpm install --frozen-lockfile
# Copiamos el proyecto a la ruta que creamos en el espacio de trabajo
COPY . .
#exponemos el puerto 3000
EXPOSE 3000
# Comando para iniciar el proyecto
CMD ["pnpm", "run", "dev"]